<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BL084-Sathish" name="test.beeforce.testcases.OfflineEmployeeCreationTitan" tests="10" failures="0" timestamp="09 May 2023 05:26:40 GMT" time="145.512" errors="1">
  <testcase name="loginAsContractor" time="3.688" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="selectModule" time="1.571" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="offlineEmployeeupload" time="6.407" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="fillEmployeeDetailsCorporate" time="39.900" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="logoutAsContractor" time="0.657" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="loginAsAdmin" time="2.918" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="openEmployeeViewAndEditPage" time="5.062" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="ReOnboardEmployeeStatus" time="52.475" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="verifyEmployeeStatus" time="9.606" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan"/>
  <testcase name="verifyDetailsInEattendance" time="23.228" classname="test.beeforce.testcases.OfflineEmployeeCreationTitan">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at test.beeforce.testcases.OfflineEmployeeCreationTitan.verifyDetailsInEattendance(OfflineEmployeeCreationTitan.java:561)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- verifyDetailsInEattendance -->
</testsuite> <!-- test.beeforce.testcases.OfflineEmployeeCreationTitan -->
