<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BL084-Sathish" name="test.beeforce.testcases.OfflineEmployeeCreation" tests="10" failures="0" timestamp="26 Mar 2023 07:49:08 GMT" time="150.198" errors="1">
  <testcase name="loginAsContractor" time="2.248" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="selectModule" time="6.733" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="offlineEmployeeupload" time="7.268" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="fillEmployeeDetailsJKC" time="45.197" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="logoutAsContractor" time="3.710" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="loginAsAdmin" time="1.699" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="openEmployeeViewAndEditPage" time="17.741" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="OnboardedEmployeeStatus" time="18.934" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="verifyEmployeeStatus" time="24.641" classname="test.beeforce.testcases.OfflineEmployeeCreation"/>
  <testcase name="verifyDetailsInEattendance" time="22.027" classname="test.beeforce.testcases.OfflineEmployeeCreation">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at test.beeforce.testcases.OfflineEmployeeCreation.verifyDetailsInEattendance(OfflineEmployeeCreation.java:539)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- verifyDetailsInEattendance -->
</testsuite> <!-- test.beeforce.testcases.OfflineEmployeeCreation -->
